parser: fix create table without name
xqueries/xdb pull request #52
Opened 2020-09-18 20:31 UTC by Shivam010

Closes #29

2020-09-18 20:33 UTC, Shivam010 commented
@xqueries/developer 
Also, I think we should discuss #51 first

2020-09-20 12:09 UTC, tsatke requested changes
Please add test cases that prove that the changes work as intended

2020-09-23 07:45 UTC, tsatke requested changes

2020-09-23 07:45 UTC, tsatke commented on internal/parser/issue29_test.go
> +		Name:  "issue29",
You are already giving a better name in the method name, please use it here as well
```suggestion
		Name:  "issue29 without table name",
```

2020-09-23 07:45 UTC, tsatke commented on internal/parser/issue29_test.go
> +		Name:  "issue29",
same here

```suggestion
		Name:  "issue29 with numeric column",
```

2020-09-23 07:45 UTC, tsatke commented on internal/parser/issue29_test.go
> +		Name:  "issue29",
```suggestion
		Name:  "issue29 with numeric column",
```

2020-09-23 08:15 UTC, tsatke approved these changes

2020-09-23 08:18 UTC, merged